# Generated by Django 3.1.6 on 2021-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=200)),
                ('cid', models.IntegerField()),
                ('structure_imageurl', models.TextField()),
                ('hnmr_imageurl', models.TextField()),
                ('cnmr_imageurl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cid', models.IntegerField()),
                ('structure_imageurl', models.TextField()),
                ('hnmr_imageurl', models.TextField()),
                ('cnmr_imageurl', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Formula_13C',
        ),
        migrations.DeleteModel(
            name='Formula_1H',
        ),
        migrations.DeleteModel(
            name='Name_13C',
        ),
        migrations.DeleteModel(
            name='Name_1H',
        ),
    ]
